import type { Meta, StoryObj } from '@storybook/react';
import { Breadcrumb } from '@/components/ui/Breadcrumb/Breadcrumb';
import HomeIcon from '@mui/icons-material/Home';
import FolderIcon from '@mui/icons-material/Folder';
import DescriptionIcon from '@mui/icons-material/Description';
import ChevronRightIcon from '@mui/icons-material/ChevronRight';

const meta = {
  title: 'UI/Navigation/Breadcrumb',
  component: Breadcrumb,
  parameters: {
    layout: 'centered',
  },
  tags: ['autodocs'],
} satisfies Meta<typeof Breadcrumb>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
    items: [
      { label: 'Home', href: '/', icon: <HomeIcon /> },
      { label: 'Documents', href: '/documents', icon: <FolderIcon /> },
      { label: 'Report.pdf', icon: <DescriptionIcon /> },
    ],
  },
};

export const WithCustomSeparator: Story = {
  args: {
    items: [
      { label: 'Home', href: '/' },
      { label: 'Documents', href: '/documents' },
      { label: 'Report.pdf' },
    ],
    separator: <ChevronRightIcon />,
  },
};

export const WithoutIcons: Story = {
  args: {
    items: [
      { label: 'Home', href: '/' },
      { label: 'Documents', href: '/documents' },
      { label: 'Projects', href: '/documents/projects' },
      { label: 'Annual Report 2024' },
    ],
  },
};

export const Collapsed: Story = {
  args: {
    items: [
      { label: 'Home', href: '/' },
      { label: 'Documents', href: '/documents' },
      { label: 'Projects', href: '/documents/projects' },
      { label: 'Client Work', href: '/documents/projects/client' },
      { label: 'Presentations', href: '/documents/projects/client/presentations' },
      { label: 'Q4 Results.pptx' },
    ],
    maxItems: 4,
  },
};

export const AutoGenerated: Story = {
  args: {
    // Não fornecemos items aqui, o componente irá gerar automaticamente baseado no pathname
    showHome: true,
  },
};
